```{r setup, include = F}
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# @@@@@ Knitr Options
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# Set root directory to the project directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())


# Set default knitr options: 
# Suppress warnings and messages, cache chunks, 
#  set default figure size to 6x8 at 300 dpi, and save a png and pdf
knitr::opts_chunk$set(warning = F, message = F, collapse = T, cache = T,
    fig.height = 6, fig.width = 8, dpi = 300, # 6x8" @ 300dpi:1800x2400=4.3MP
    dev = c('png', 'pdf'), dev.args = list(pdf = list(onefile = F)))

```

overdispersion test
```{r}
overdispersion_test <- function(model, type = "pearson"){
    
    # Get the pearson residuals
    residuals <- resid(model, type = type)
    
    # Get the residual degrees of freedom of the model
    df <- df.residual(model)
    
    # Sum of residual deviance
    dev <- sum(residuals ^ 2)
    
    # Overdispersion = sum of squared residuals / residual degrees of freedom
    ratio <- round(dev / df, 3)
    
    # P-value 
    pvalue <- round(pchisq(dev, df, lower.tail = FALSE), 3)
    
    # Get the formula
    f = paste(as.character(formula(model))[2:3], collapse = " ~ ")
    
    # Get the model name
    name <- deparse(substitute(model))
    cat("Overdispersion ratio for model:", name, "\nformula:", f, 
        "\n\nAcceptable range: 1 - 1.4\nOverdispersion ratio:",
        ratio, " df:", df, " p =", pvalue, "\n", 
        ifelse(pvalue < 0.05, "Data are OVERDISPERSED\n", 
        "Data are NOT OVERDISPERSED\n"))
    # Return all the parameters
    return(c(ratio = ratio, deviance = dev, df = df, pvalue = pvalue))
    
}
```



loading in packages
```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(metafor)
library(VGAM)
library(sjPlot)
library(lme4)
library(car)
library(emmeans)
library(lubridate)
library(glmmTMB)

```
loading in data

```{r}

data <- read.csv("Data/cubee2026.csv")


```
subtracting mortality, adding day column, and obs 
```{r}
dat <- data %>%
  mutate(
    Date = mdy(Date),
    NDB = as.numeric(NDB),
    TotalM = as.numeric(TotalM),
    Treatment = as.factor(Treatment)
  ) %>%
  arrange(CageID, Date) %>%
  group_by(CageID) %>%
  mutate(
    TotalM_cage = first(na.omit(TotalM)),
    TotalD = cumsum(replace_na(NDB, 0)),
    Alive = TotalM_cage - TotalD,
    Day = as.numeric(Date - min(Date, na.rm = TRUE)),
   Risk = as.numeric(Alive + NDB),
   logRisk = log(Risk)) %>%
  filter(!is.na(logRisk)) %>%
  ungroup() %>%
    mutate(obs_ID = factor(dplyr::row_number())) %>%
  select(-TotalM_cage)

```
models
```{r}

#cumulative survival
mod1 <-  glmmTMB(cbind(Alive, TotalD) ~ Treatment * Day +
                  (1 | CageID) + (1 | obs_ID),
            family = binomial(), data = dat) 

overdispersion_test(mod1) 


mod2 <-  glmmTMB(cbind(Alive, TotalD) ~ Treatment* Day +
                  (1 | obs_ID),
            family = binomial(), data = dat) 

overdispersion_test(mod2)

mod3 <- glmmTMB(cbind(Alive, TotalD) ~ Treatment + Day +
                  (1 | CageID) + (1 | obs_ID),
            family = binomial(), data = dat) 

overdispersion_test(mod3)

mod4 <- glmmTMB(cbind(Alive, TotalD) ~ Treatment + Day +
                  (1 | obs_ID),
            family = binomial(), data = dat) 

overdispersion_test(mod4)

AIC(mod1,mod2, mod3, mod4) #mod1 is a better model
```

plotting model
```{r}
plot_model(mod1, type = "pred",
           terms = c("Day [all]", "Treatment"),
           title = "") +
  labs(x = "Day", y = "Pr(Bee Survival)", color = "Treatment") +
  theme_minimal(base_size = 16)

summary(mod1)
car::Anova(mod1)
```


model summary and post-hoc tests
```{r}
summary(mod1)
car::Anova(mod1)

library(emmeans)

emm_day <- emmeans(
  mod1,
  ~ Treatment | Day,
  at = list(Day = c(0:28)),
  type = "response"
)

emm_day
```

reduced dataset
```{r}

datre <- dat %>% 
  filter(dat$Day <= 28)

```

model for datre

``` {r}
mod5 <-  glmmTMB(cbind(Alive, TotalD) ~ Treatment * Day +
                  (1 | CageID) + (1 | obs_ID),
            family = binomial(), data = datre) 

mod6 <-  glmmTMB(cbind(Alive, TotalD) ~ Treatment * Day ,
            family = binomial(), data = datre) 

mod7 <-  glmmTMB(cbind(Alive, TotalD) ~ Treatment * Day +
                  (1 | CageID) ,
            family = binomial(), data = datre) 

mod8 <-  glmmTMB(cbind(Alive, TotalD) ~ Treatment * Day +
                   (1 | obs_ID),
            family = binomial(), data = datre) 

overdispersion_test(mod5) #BEST AIC
overdispersion_test(mod6) #over
overdispersion_test(mod7) #over
overdispersion_test(mod8)
AIC(mod5, mod6, mod7, mod8)

```

plotting model mod5
```{r}
plot_model(mod5, type = "pred",
           terms = c("Day [all]", "Treatment"),
           title = "") +
  labs(x = "Day", y = "Pr(Bee Survival)", color = "Treatment") +
  theme_minimal(base_size = 16)

summary(mod1)
car::Anova(mod1)
```


model summary and post-hoc tests
```{r}
summary(mod5)
car::Anova(mod5)

library(emmeans)

emm_dayre <- emmeans(
  mod5,
  ~ Treatment | Day,
  at = list(Day = c(0:28)),
  type = "response"
)

emm_dayre
```





















